# Generated by Django 5.0.7 on 2026-09-20 18:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("APPROVAL_REQUIRED", "Approval Required"),
                            ("DUPLICATE_WARNING", "Duplicate Warning"),
                            ("PAYMENT_DUE", "Payment Due"),
                            ("PROCESSING_COMPLETE", "Processing Complete"),
                            ("EXCEPTION_RAISED", "Exception Raised"),
                            ("INVOICE_REJECTED", "Invoice Rejected"),
                            ("PAYMENT_COMPLETED", "Payment Completed"),
                            ("GENERAL", "General"),
                        ],
                        default="GENERAL",
                        max_length=30,
                    ),
                ),
                ("message", models.CharField(max_length=500)),
                ("link", models.CharField(blank=True, default="", max_length=255)),
                ("is_read", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "notifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_read"],
                        name="notificatio_user_id_a4dd5c_idx",
                    )
                ],
            },
        ),
    ]
