# Generated by Django 5.0.7 on 2026-09-21 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("APPROVAL_REQUIRED", "Approval Required"),
                    ("APPROVAL_REMINDER", "Approval Reminder"),
                    ("APPROVAL_ESCALATED", "Approval Escalated"),
                    ("DUPLICATE_WARNING", "Duplicate Warning"),
                    ("PAYMENT_DUE", "Payment Due"),
                    ("PROCESSING_COMPLETE", "Processing Complete"),
                    ("EXCEPTION_RAISED", "Exception Raised"),
                    ("INVOICE_REJECTED", "Invoice Rejected"),
                    ("PAYMENT_COMPLETED", "Payment Completed"),
                    ("GENERAL", "General"),
                ],
                default="GENERAL",
                max_length=30,
            ),
        ),
    ]
