# Generated by Django 5.0.7 on 2026-09-20 18:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Vendor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("code", models.CharField(max_length=32, unique=True)),
                ("gstin", models.CharField(blank=True, default="", max_length=15)),
                ("pan", models.CharField(blank=True, default="", max_length=10)),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                ("phone", models.CharField(blank=True, default="", max_length=30)),
                (
                    "contact_person",
                    models.CharField(blank=True, default="", max_length=150),
                ),
                (
                    "address_line1",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "address_line2",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("city", models.CharField(blank=True, default="", max_length=100)),
                ("state", models.CharField(blank=True, default="", max_length=100)),
                ("pincode", models.CharField(blank=True, default="", max_length=12)),
                (
                    "country",
                    models.CharField(blank=True, default="India", max_length=100),
                ),
                ("category", models.CharField(blank=True, default="", max_length=100)),
                (
                    "department",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("payment_terms_days", models.PositiveIntegerField(default=30)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SUBMITTED", "Submitted"),
                            ("UNDER_REVIEW", "Under Review"),
                            ("APPROVED", "Approved"),
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vendors_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "vendors",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="VendorBankDetails",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("account_holder_name", models.CharField(max_length=255)),
                ("account_number", models.CharField(max_length=40)),
                ("bank_name", models.CharField(max_length=150)),
                ("ifsc_code", models.CharField(max_length=15)),
                ("branch", models.CharField(blank=True, default="", max_length=150)),
                ("is_verified", models.BooleanField(default=False)),
                (
                    "vendor",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank_details",
                        to="vendors.vendor",
                    ),
                ),
            ],
            options={
                "db_table": "vendor_bank_details",
            },
        ),
        migrations.CreateModel(
            name="VendorDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("file", models.FileField(upload_to="vendor_documents/")),
                (
                    "document_type",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="vendors.vendor",
                    ),
                ),
            ],
            options={
                "db_table": "vendor_documents",
            },
        ),
        migrations.AddIndex(
            model_name="vendor",
            index=models.Index(fields=["name"], name="vendors_name_a8eecc_idx"),
        ),
        migrations.AddIndex(
            model_name="vendor",
            index=models.Index(fields=["gstin"], name="vendors_gstin_866bef_idx"),
        ),
        migrations.AddIndex(
            model_name="vendor",
            index=models.Index(fields=["status"], name="vendors_status_079e23_idx"),
        ),
    ]
