# Generated by Django 5.0.7 on 2026-09-20 18:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("LOGIN", "Login"),
                            ("LOGOUT", "Logout"),
                            ("UPLOAD", "Invoice Upload"),
                            ("OCR_PROCESS", "OCR Processing"),
                            ("FIELD_EDIT", "Field Edit"),
                            ("VALIDATE", "Validation Run"),
                            ("EXCEPTION_CREATE", "Exception Created"),
                            ("EXCEPTION_RESOLVE", "Exception Resolved"),
                            ("PO_MATCH", "PO Matching Run"),
                            ("APPROVAL", "Approved"),
                            ("REJECTION", "Rejected"),
                            ("REQUEST_CHANGES", "Changes Requested"),
                            ("VENDOR_CREATE", "Vendor Created"),
                            ("VENDOR_UPDATE", "Vendor Updated"),
                            ("PAYMENT_REQUEST", "Payment Request Created"),
                            ("PAYMENT_STATUS_CHANGE", "Payment Status Changed"),
                            ("CREATE", "Created"),
                            ("UPDATE", "Updated"),
                            ("DELETE", "Deleted"),
                        ],
                        max_length=32,
                    ),
                ),
                ("entity_type", models.CharField(max_length=64)),
                ("entity_id", models.CharField(blank=True, default="", max_length=64)),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("previous_value", models.JSONField(blank=True, null=True)),
                ("new_value", models.JSONField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                "db_table": "audit_logs",
                "ordering": ["-created_at"],
            },
        ),
    ]
