# Generated by Django 5.0.7 on 2026-09-21 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit_logs", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("LOGIN", "Login"),
                    ("LOGOUT", "Logout"),
                    ("UPLOAD", "Invoice Upload"),
                    ("OCR_PROCESS", "OCR Processing"),
                    ("FIELD_EDIT", "Field Edit"),
                    ("VALIDATE", "Validation Run"),
                    ("EXCEPTION_CREATE", "Exception Created"),
                    ("EXCEPTION_RESOLVE", "Exception Resolved"),
                    ("PO_MATCH", "PO Matching Run"),
                    ("APPROVAL", "Approved"),
                    ("REJECTION", "Rejected"),
                    ("REQUEST_CHANGES", "Changes Requested"),
                    ("APPROVAL_REMINDER", "Approval Reminder Sent"),
                    ("APPROVAL_ESCALATED", "Approval Escalated"),
                    ("VENDOR_CREATE", "Vendor Created"),
                    ("VENDOR_UPDATE", "Vendor Updated"),
                    ("PAYMENT_REQUEST", "Payment Request Created"),
                    ("PAYMENT_STATUS_CHANGE", "Payment Status Changed"),
                    ("CREATE", "Created"),
                    ("UPDATE", "Updated"),
                    ("DELETE", "Deleted"),
                ],
                max_length=32,
            ),
        ),
    ]
