# Generated by Django 5.0.7 on 2026-09-20 18:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("purchase_orders", "0001_initial"),
        ("vendors", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "invoice_number",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "vendor_name_raw",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "po_number_raw",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("gstin", models.CharField(blank=True, default="", max_length=15)),
                ("invoice_date", models.DateField(blank=True, null=True)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("currency", models.CharField(default="INR", max_length=6)),
                (
                    "subtotal",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "cgst",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "sgst",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "igst",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "discount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "payment_terms",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "department",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("UPLOADED", "Uploaded"),
                            ("PROCESSING", "Processing"),
                            ("EXTRACTED", "Extracted"),
                            ("VALIDATED", "Validated"),
                            ("EXCEPTION", "Exception"),
                            ("PENDING_APPROVAL", "Pending Approval"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("PAYMENT_PENDING", "Payment Pending"),
                            ("PAID", "Paid"),
                        ],
                        default="UPLOADED",
                        max_length=20,
                    ),
                ),
                (
                    "ocr_provider",
                    models.CharField(blank=True, default="", max_length=30),
                ),
                ("ocr_confidence", models.FloatField(blank=True, null=True)),
                (
                    "ocr_confidence_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("HIGH", "High"),
                            ("MEDIUM", "Medium"),
                            ("LOW", "Low"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("ocr_raw_text", models.TextField(blank=True, default="")),
                (
                    "po_match_status",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                (
                    "purchase_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoices",
                        to="purchase_orders.purchaseorder",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoices_uploaded",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoices",
                        to="vendors.vendor",
                    ),
                ),
            ],
            options={
                "db_table": "invoices",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InvoiceDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("file", models.FileField(upload_to="invoices/")),
                ("file_name", models.CharField(max_length=255)),
                ("file_type", models.CharField(max_length=20)),
                ("file_size", models.PositiveIntegerField(default=0)),
                ("page_count", models.PositiveIntegerField(default=1)),
                ("is_primary", models.BooleanField(default=True)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="invoices.invoice",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "invoice_documents",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InvoiceException",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "exception_type",
                    models.CharField(
                        choices=[
                            ("MISSING_VENDOR", "Missing Vendor"),
                            ("INVALID_GSTIN", "Invalid GSTIN"),
                            ("DUPLICATE_INVOICE", "Duplicate Invoice"),
                            ("AMOUNT_MISMATCH", "Amount Mismatch"),
                            ("MISSING_PO", "Missing PO"),
                            ("OCR_LOW_CONFIDENCE", "OCR Low Confidence"),
                            ("MISSING_MANDATORY_FIELD", "Missing Mandatory Field"),
                            ("PO_MISMATCH", "PO Mismatch"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="MEDIUM",
                        max_length=10,
                    ),
                ),
                ("description", models.CharField(max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("RESOLVED", "Resolved"),
                            ("REJECTED", "Rejected"),
                            ("OVERRIDDEN", "Overridden"),
                        ],
                        default="OPEN",
                        max_length=15,
                    ),
                ),
                (
                    "resolution_comment",
                    models.CharField(blank=True, default="", max_length=1000),
                ),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="exceptions_assigned",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exceptions",
                        to="invoices.invoice",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="exceptions_resolved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "invoice_exceptions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InvoiceExtractedField",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("field_name", models.CharField(max_length=60)),
                ("value", models.CharField(blank=True, default="", max_length=500)),
                ("confidence", models.FloatField(default=0)),
                ("is_mandatory", models.BooleanField(default=False)),
                ("is_edited", models.BooleanField(default=False)),
                (
                    "validation_status",
                    models.CharField(default="PENDING", max_length=20),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extracted_fields",
                        to="invoices.invoice",
                    ),
                ),
            ],
            options={
                "db_table": "invoice_extracted_fields",
            },
        ),
        migrations.CreateModel(
            name="InvoiceLineItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("line_no", models.PositiveIntegerField(default=1)),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "quantity",
                    models.DecimalField(decimal_places=2, default=1, max_digits=12),
                ),
                (
                    "unit_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "tax_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="line_items",
                        to="invoices.invoice",
                    ),
                ),
            ],
            options={
                "db_table": "invoice_line_items",
                "ordering": ["line_no"],
            },
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["invoice_number"], name="invoices_invoice_7778bc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(fields=["status"], name="invoices_status_07776b_idx"),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(fields=["gstin"], name="invoices_gstin_864a0c_idx"),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["-created_at"], name="invoices_created_3daf52_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoiceexception",
            index=models.Index(fields=["status"], name="invoice_exc_status_327044_idx"),
        ),
        migrations.AddIndex(
            model_name="invoiceexception",
            index=models.Index(
                fields=["severity"], name="invoice_exc_severit_f13f29_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="invoiceextractedfield",
            unique_together={("invoice", "field_name")},
        ),
    ]
