# Generated by Django 5.0.7 on 2026-09-20 18:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("invoices", "0001_initial"),
        ("vendors", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("request_number", models.CharField(max_length=50, unique=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("currency", models.CharField(default="INR", max_length=6)),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("BANK_TRANSFER", "Bank Transfer (NEFT/RTGS)"),
                            ("CHEQUE", "Cheque"),
                            ("UPI", "UPI"),
                            ("CARD", "Card"),
                        ],
                        default="BANK_TRANSFER",
                        max_length=20,
                    ),
                ),
                ("requested_date", models.DateField(auto_now_add=True)),
                ("due_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PAYMENT_PENDING", "Payment Pending"),
                            ("PROCESSING", "Processing"),
                            ("PAID", "Paid"),
                            ("FAILED", "Failed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PAYMENT_PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "invoice",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_request",
                        to="invoices.invoice",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payment_requests_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_requests",
                        to="vendors.vendor",
                    ),
                ),
            ],
            options={
                "db_table": "payment_requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "transaction_ref",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("payment_date", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PAYMENT_PENDING", "Payment Pending"),
                            ("PROCESSING", "Processing"),
                            ("PAID", "Paid"),
                            ("FAILED", "Failed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PROCESSING",
                        max_length=20,
                    ),
                ),
                ("bank_response", models.JSONField(blank=True, null=True)),
                ("advice_generated", models.BooleanField(default=False)),
                (
                    "advice_file",
                    models.FileField(
                        blank=True, null=True, upload_to="payment_advice/"
                    ),
                ),
                (
                    "processed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "payment_request",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment",
                        to="payments.paymentrequest",
                    ),
                ),
            ],
            options={
                "db_table": "payments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="paymentrequest",
            index=models.Index(fields=["status"], name="payment_req_status_65728f_idx"),
        ),
    ]
